[tool.poetry]
name = "seedhelper"
version = "0.1.0"
description = ""
authors = ["Louis Pagnier"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
setuptools = "^69.2.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
